### PR TITLE
`neutral_atom_compile` client

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Comment by vtomole** [comment]
@richrines1 Ready for review.

**Comment by richrines1** [comment]
it looks like this depends on supertechlabs/cirq-superstaq#126 and will require similar changes to `qiskit_superstaq/superstaq_provider.py` correct?

**Comment by vtomole** [comment]
Yes. Will make those now.

**Comment by richrines1** [comment]
cool, otherwise lgtm

**Review by richrines1 — APPROVED** [review]

**Pull request merged**
